version: "3.9"
services:
  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:6-fpm
    container_name: wp-wordpress
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - wp
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  wordpress-cli:
    image: wordpress:cli
    container_name: wp-cli
    env_file:
      - .env
    depends_on:
      - wordpress
      - database
    networks:
      - wp
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
    command: tail -f /dev/null

  database:
    # default port 3306
    image: mysql:8
    container_name: wp-database
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - wp
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:80" # http
      - "8443:443" # https
    depends_on:
      - wordpress
    networks:
      - wp
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  # adminer - bring up only as needed - bypasses nginx
  adminer:
    # default port 8080
    image: adminer:4
    container_name: wp-adminer
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - wp
    ports:
      - "9000:8080"

networks:
  wp:
    name: wp-net
    driver: bridge
